### ISSUE TITLE
Book05_Ch08_Page15 Eq(25)

### ISSUE THREAD

**Issue by Hurricane-k** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#20]
Eq(25) 右边第一项 $(x_2 -E(X_2|X_1=6.5))$ 这里少了平方，因为这里是计算条件方差 $var(X_2|X_1=6.5)$

**Comment by Visualize-ML** [comment]
这个问题没写完？章号也没有

**Comment by Hurricane-k** [comment]
我已经修改了问题了
![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/56281608/b7ef91cc-a153-4fbb-869b-7e27aa0a44e8)

**Comment by Hurricane-k** [comment]
不知道您那边为何没有显示修改之后的完整问题

**Comment by Visualize-ML** [comment]
谢谢你！后面我会统一修改！统计至简，也会有纠错赠书表达感谢！请多多批评！

**Comment by Visualize-ML** [comment]
把你的姓名、地址、电话发到我的gmail。我把你加到，矩阵力量，纠错赠书名单里。

**Comment by Hurricane-k** [comment]
还是要非常感谢您的无私分享，对我科研有莫大的帮助，十分感谢！

**Comment by Hurricane-k** [comment]
Dear Dr. Ginger


姓名 Cary. H
地址 江苏省 泰州市 靖江市 城北园区北二环裕安苑tu兔喜生活
电话 15651920118


非常感谢您的书，在我的科研道路上有很大的帮助


Best Regards,




| |
RUIKAI HE
|
|
***@***.***
|
---- Replied Message ----
| From | Iris Series: From Arithmetic Basics to Machine ***@***.***> |
| Date | 5/26/2023 19:58 |
| To | ***@***.***> |
| Cc | Carry, ***@***.***> ,
***@***.***> |
| Subject | Re: [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics] Book05_Ch08_Page15 Eq(25) (Issue #20) |

把你的姓名、地址、电话发到我的gmail。我把你加到，矩阵力量，纠错赠书名单里。
