### ISSUE TITLE
Book05_Ch09_Page3

### ISSUE THREAD

**Issue by umarL1123** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#22]
”回顾上一章介绍”应为"回顾第七章介绍"，另外在第七章中介绍正态分布时是否可以补充棣莫弗（Abraham de Moivre）在求二项分布的渐近公式时得到正态分布的过程。

**Comment by Visualize-ML** [comment]
谢谢你！七月份统一修改！请继续批评！

Cheers
