### ISSUE TITLE
Book5_CH00_page2

### ISSUE THREAD

**Issue by CanYellow** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#29]
拿破仑曾说“数学的日臻完善和这个国强民富息息相关。 ” 是否改为 拿破仑曾说“数学的日臻完善和这个国强民富息息相关”。  更好(调换右引号与句号的位置)？

”历史是过去，又属于现在，同时在指引未来。 ” 这里的左引号似乎是错的，且是否改为 “历史是过去，又属于现在，同时在指引未来 ” 。 更好(调换右引号与句号的位置)?

**Comment by Visualize-ML** [comment]
引号使用好像还真没错，引号内是一句或一段完整的话，且引文独立使用时，引号内应当保留句号等句末点号。请继续批评指正。
