### ISSUE TITLE
Book5_CH02 表格描述排版错位

### ISSUE THREAD

**Issue by HairlessVillager** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#30]
![QQ截图20230827103008.png](https://x.imgs.ovh/x/2023/08/27/64eab57d61da8.png)

`表 1. 鸢尾花四阶矩`的文字描述在 p.29，表格本体在 p.30

**Comment by Visualize-ML** [comment]
谢谢你，上传的版本都是作者草稿。最终排版、内容以出版社版本为准。请继续批评指正。

Cheers,
James
