### ISSUE TITLE
Book5_Ch05 图4  圆周率小数点后数字的分布 

### ISSUE THREAD

**Issue by zhangshuiyong** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#31]
图中的频数总数有问题（应该是从1000位开始，不是100）

![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/1655233/e85f38c5-65a5-4a9d-986d-0148de94c616)

**Comment by Visualize-ML** [comment]
谢谢你，确实标错了。会在排版稿修改。请继续批评指正。

Cheers
