### ISSUE TITLE
Book5_Ch04_Page16 方差的技巧的几何意义是否能联系前面的方差的矩阵角度与毕达哥拉斯定理？

### ISSUE THREAD

**Issue by zhangshuiyong** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#32]
<img width="564" alt="image" src="https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/1655233/c26acfd7-416a-472a-8bfd-cdba7f340633">

![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/1655233/dd409a07-d756-43c7-b099-95519bd587a0)

![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/1655233/3442b8d0-675e-459d-abc8-9eee4c0aac04)

**Comment by Visualize-ML** [comment]
谢谢，这个视角确实很好！我已经记下来了。请继续批评指正。
