### ISSUE TITLE
Book5_Ch03 P30公示43在一般书上做为独立性定义的，在这本书做为推论不知是有什么特别考虑的

### ISSUE THREAD

**Issue by elecliu** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#35]
此处一般书上做为定义也许是从形式最简的做为出发点考虑再由此推出其他定理。这确实和我们平时的思考习惯不大一样，我以前学习的时候也受此困扰，感觉因果关系似乎反了，但是后来觉得数学本身从抽象的最简单形通过逻辑推理构造整个系统，才接受了这个因果推理关系，望您指正，不当之处请赐教。

**Comment by Visualize-ML** [comment]
谢谢你，很多资料会调换42、43式顺序。这本书42放在前面是觉得这个式子更好理解，43则是在涉及运算中用的更多。请继续批评指正。
