### ISSUE TITLE
请解释一下这个怎么来的？谢谢

### ISSUE THREAD

**Issue by zzmjp** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#37]
![屏幕截图 2023-09-20 182834](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/145321337/043ad802-3323-4512-9f87-f276a76c025a)

![屏幕截图 2023-09-20 171652](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/145321337/ae469257-71da-4e8e-8f63-41b3e34cf3fd)

**Comment by zzmjp** [comment]
统计至简24章，线性回归部分优化部分

**Comment by Visualize-ML** [comment]
谢谢你，这是多元微积分部分的内容。你可以参考《矩阵力量》的第17章。
https://github.com/Visualize-ML/Book4_Power-of-Matrix
