### ISSUE TITLE
一些翻译和符号问题

### ISSUE THREAD

**Issue by USTCmyw** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#39]
1. 我注意到你把数据结构dataframe翻译为“数据帧”，但是"数据帧"的英文原名叫data frame(中间有一个空格)，是计算机网络中的一个术语，和dataframe毫无关系。希望能采用其他的译名，如数据筐，或者不翻译，直接采用英文名称。
2. cdf的翻译不一致。有些地方译为"累积分布函数"，有些地方又译为"累积概率密度"，应该按照英文Cumulative Distribution Function翻译为"累积分布函数"。
3. 一些符号问题，比如第5章p16公式(23)，数学教材上一般的写法是$p(X=k) = \frac{\exp{-\lambda}\lambda^k}{k!}$，通常将大写的X用来表示随机变量，取值为整数的，用字母$k$来代表。小写的$x$通常用来代表密度函数或者分布函数的自变量。
4. 一些地方不太规范，比如第6章p16图20，坐标轴是X=x和Y=y。我能理解你是想说随机变量X，Y可能的取值，但是X=x在坐标轴上是不规范的写法。两边一个是随机变量一个是数，$X=x$在数学教材里表示样本空间$\Omega$，使得$X(\Omega)=x$

**Comment by USTCmyw** [comment]
1. 关于第4点，第六章p19图25左边坐标轴就更合理。
2. 概率密度函数里，随机变量的数字应该写在下标上，比如图25右边和式35等一些地方的PDF的X1，X2。
3. 关于字体的问题，book5里使用的字体，大写的X和小写的x容易搞混。

**Comment by USTCmyw** [comment]
以及ch6 p26 图35，左图，阴影部分应该是f_{X2}(x2)吧？

**Comment by Visualize-ML** [comment]
谢谢你！这些建议都太好了！非常感谢。鸢尾花书对纠错多的读者有赠书感谢，下一批是《编程不难》的赠书。方便的话，请发我你的邮寄信息，姓名地址电话。邮箱地址，在PDF左下角。《编程不难》明年初上架，一旦上架由出版社安排寄送。

祝好！

**Comment by USTCmyw** [comment]
几处笔误和记号问题：
1. ch8 p10 公式13，第二个式子，条件方差的表达式有误，等式左边应该是var(Y|X)。
2. ch8 p12 公式19，等号右边第一项，应该为 E(cov(X_1|Y, X_2|Y))。
3. 在条件概率中经常有X=x,Y=y这样的写法，表示随机变量的取值，但是小写的x,y又经常作为概率密度函数的自变量，容易混淆。可以将随机变量和概率密度函数的固定取值记为x_0, y_0。
4. ch9 p3公式1以及后面的地方，高斯函数指数项里的负号应该放在分数线外面

**Comment by Visualize-ML** [comment]
谢谢你，请继续批评指正！

Cheers
James
