### ISSUE TITLE
15.10 产生满足特定相关性的随机数

### ISSUE THREAD

**Issue by USTCmyw** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#40]
说实话，"Cholesky分解"这一小节，我其实没有看明白这个X=ZR+EX的每一项。
这一节似乎是生成满足给定协方差矩阵的**样本**。首先生成矩阵Z满足N(0,I_{D*D})，这个矩阵Z怎么定义的？我们通常说满足D维高斯分布，指的是D个数的关系，这里的n * D维矩阵，是n个这样的D个数的组合吗？
我看24式左边，是样本的计算方式，等式最右边又把每个z_i当成了随机变量。

我在网上查阅的其他资料，都是利用线性变换，生成满足给定协方差矩阵的**随机向量**

**Comment by Visualize-ML** [comment]
获得满足特定协方差的多元随机数，一般会用Cholesky分解的结果，也有用EVD分解结果。这一节的目的是向大家展示，两种方法本质上是一致的，即对协方差矩阵求“方根”。

U就是两个不同分解的联系，U有无数个，也就是说，协方差的方根有无数个；而Cholesky和EVD帮我们找到了两个特例。

Z是IID，ZR就是线性变换。E(X) 仅仅提供平移。
