### ISSUE TITLE
作者您好，请问Book5_Ch02_Python_Codes中的iris数据集来自哪里呀，方便提供吗？

### ISSUE THREAD

**Issue by Love-percation** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#41]
我从网上找了一个iris数据集，数据集格式为图中所示，sepal_length，sepal_width,petal_length,petal_width,species这五列。
![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/62577309/048763bb-daa5-47c0-83b1-37f6a0cd57ff)

运行代码的时候，显示116行代码：sns.histplot(iris_sns,x="price",y="cut",bins=20)中，ValueError: Could not interpret value `price` for `x`. An entry with this name does not appear in `data`.

怀疑是网上的数据集iris中缺少了price这一列，所以请问您方便提供您使用的数据集吗？

**Comment by Love-percation** [comment]
在没有采用网上的iris数据集时，在服务器上跑ch2源代码。没有出现116中的price问题，也可能是因为我在数据集的特征中加了一列price。
但是出现了137这样的问题。
![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/62577309/dbd61f21-f66c-404a-a68e-6ee200b48767)
ValueError                                Traceback (most recent call last)
![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/62577309/e94c5d73-457d-445f-b8f4-b82ed2b93f8a)

**Comment by Visualize-ML** [comment]
seaborn，plotly，scikit learn都有数据。直接导入即可。建议参考，编程不难第19章。

https://github.com/Visualize-ML
