### ISSUE TITLE
Book5_Ch20 page24页图22的(h)兔子数量标签不正确

### ISSUE THREAD

**Issue by zhezhia** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#42]
![Screenshot_20231109_224806_com orion notein](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/105048628/1d067443-66e3-4e81-a0d0-8b4338a18ec1)
兔子数量不应为3

**Comment by Visualize-ML** [comment]
谢谢你，应该是32，请继续批评指正。
