### ISSUE TITLE
Ch04 | Page7 | 4.1 随机 天地不仁，以万物为刍狗 | 随机变量的函数

### ISSUE THREAD

**Issue by lwy4199** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#44]
> 特别地，如果 h() 为线性函数，从X 到 Y 进行的是线性变换，比如：
> $Y = h( X ) = aX + b$

因为式中有b，此处是否应为“从X 到 Y 进行的线性映射（仿射变换，原点有可能改变）”？

**Comment by lwy4199** [comment]
这是否可以理解为样本空间分布的转换呢？而分布转换可能伴随着原点改变。

**Comment by lwy4199** [comment]
7.7 卡方分布：若干IID 标准正态分布平方和
这一章节对自由度的定义是否应该是“k个相互独立的随机变量”而不是“n个相互独立的随机变量”？

**Comment by lwy4199** [comment]
![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/70910166/cf27b9cc-8b0e-4fea-858a-7c32394f36bb)
Ch8 第2节 离散随机变量：条件方差
是否为笔误，应为 重叠方差定理？

**Comment by lwy4199** [comment]
Ch8 第4节 条件期望E(Y|X = x)
等式(46)
![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/70910166/9f494e60-2f1b-4c7d-be01-696ee6ba3846)
给定条件X = x, 积分区间是否应该去掉无穷记号，改为特定区间？

**Comment by lwy4199** [comment]
Ch9 第三节：标准高斯分布：期望为0，标准差为1，“Z 分数：一种以标准差为单位的度量尺度”小节
图11纵轴是否应为PPF，对应的文字描述是否应为：图11 所示为标准正态分布随机变量 z 值到 PPF 值的映射关系。另外图11是否画反了，并非反函数。

**Comment by lwy4199** [comment]
Ch9 第四节：9.4 68-95-99.7 法则，关于法则的描述：“一元高斯分布有所谓的68-95-99.7 法则(68-95-99.7 Rule)，具体是指一组近乎满足正态分布的样本数据”，是否应该是“近乎满足**标准**正态分布的样本数据”？

**Comment by lwy4199** [comment]
Ch9 第七节：QQ 图：分位-分位图
对于图23的描述：“我们首先计算每个样本 y(i) 对应的 ECDF 值，然后再利用标准正态分布 PPF 将 ECDF 值转化为 x(i)。”是否应为“我们首先计算每个样本 y(i) 对应的 inverse ECDF 值，然后再利用标准正态分布 PPF 将 CDF 值转化为 x(i)。”?
图23左下角纵轴是否为 inverse ECDF，横轴为 PPF ？

**Comment by lwy4199** [comment]
Ch9 第八节：从距离到一元高斯分布。“几何变换：平移 + 缩放”小节

描述：“假设 X 是连续随机变量，它的概率密度函数PDF 为fX(x)，经过如下线性变换得到Y”，是否应为“假设 X 是**服从正态分布**的连续随机变量，它的概率密度函数PDF 为fX(x)，经过如下线性变换得到Y”

**Comment by lwy4199** [comment]
Ch11 第四节 等式(37)
请问如何理解等式(37)：分子第一项的分子是σ1和σ2相减；分母ρ(1,2)σ1σ2代表的含义

**Comment by Visualize-ML** [comment]
> > 特别地，如果 h() 为线性函数，从X 到 Y 进行的是线性变换，比如：
> > Y=h(X)=aX+b
> 
> 因为式中有b，此处是否应为“从X 到 Y 进行的线性映射（仿射变换，原点有可能改变）”？

谢谢你，的确，从线性代数角度来看，这是仿射变换；但是，在概率统计中，这个一般叫线性变换。

再版时，会加一句说明。

**Comment by Visualize-ML** [comment]
> 7.7 卡方分布：若干IID 标准正态分布平方和 这一章节对自由度的定义是否应该是“k个相互独立的随机变量”而不是“n个相互独立的随机变量”？

谢谢你！中间把n改成了k，有些地方改漏了。

**Comment by Visualize-ML** [comment]
> ![image](https://private-user-images.githubusercontent.com/70910166/292669406-cf27b9cc-8b0e-4fea-858a-7c32394f36bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTA3MzcsIm5iZiI6MTcwMzcxMDQzNywicGF0aCI6Ii83MDkxMDE2Ni8yOTI2Njk0MDYtY2YyN2I5Y2MtOGIwZS00ZmVhLTg1OGEtN2MzMjM5NGYzNmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDIwNTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYTFjZjllYzM2ZDQ3NjA1YTFlMzY3ZDgyYzQwMjllMzRmOGZmNGYxZGMxM2IwYjlmMDU2ZDAyZjYxNzEyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9xPjaaQPLwzUvn02mCiQm-XyeZDLcM4kzA_rsUXuX0k) Ch8 第2节 离散随机变量：条件方差 是否为笔误，应为 重叠方差定理？

确实是笔误，请继续批评指正。

**Comment by Visualize-ML** [comment]
> Ch8 第4节 条件期望E(Y|X = x) 等式(46) ![image](https://private-user-images.githubusercontent.com/70910166/292676736-9f494e60-2f1b-4c7d-be01-696ee6ba3846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTA3MzcsIm5iZiI6MTcwMzcxMDQzNywicGF0aCI6Ii83MDkxMDE2Ni8yOTI2NzY3MzYtOWY0OTRlNjAtMmYxYi00YzdkLWJlMDEtNjk2ZWU2YmEzODQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDIwNTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMzI2NGJhZjg2YjIyNTk4OTEwMDdjMWU0OTIwZjAyZDI0ZjQ0YzExNjk0N2FjZmIyNzFjYmZiYjNjNjQ0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O4Jw6cK8U8nD4bT25ykfzBqyk16Ej-NQ5W2_0_jTe4U) 给定条件X = x, 积分区间是否应该去掉无穷记号，改为特定区间？

这个偏积分是一般意义上的消除某个随机变量求解边缘PDF过程。

**Comment by Visualize-ML** [comment]
> Ch9 第三节：标准高斯分布：期望为0，标准差为1，“Z 分数：一种以标准差为单位的度量尺度”小节 图11纵轴是否应为PPF，对应的文字描述是否应为：图11 所示为标准正态分布随机变量 z 值到 PPF 值的映射关系。另外图11是否画反了，并非反函数。

你是对的，这里图文不符。应该画一幅类似，图9.6右图，的图像。

**Comment by Visualize-ML** [comment]
> Ch9 第七节：QQ 图：分位-分位图 对于图23的描述：“我们首先计算每个样本 y(i) 对应的 ECDF 值，然后再利用标准正态分布 PPF 将 ECDF 值转化为 x(i)。”是否应为“我们首先计算每个样本 y(i) 对应的 inverse ECDF 值，然后再利用标准正态分布 PPF 将 CDF 值转化为 x(i)。”? 图23左下角纵轴是否为 inverse ECDF，横轴为 PPF ？

ECDF的取值范围在 [0, 1]；
虽然，左上角子图的横轴是ECDF值，但是这个函数还是x >>> ecdf(x) 的映射

**Comment by Visualize-ML** [comment]
> Ch9 第八节：从距离到一元高斯分布。“几何变换：平移 + 缩放”小节
> 
> 描述：“假设 X 是连续随机变量，它的概率密度函数PDF 为fX(x)，经过如下线性变换得到Y”，是否应为“假设 X 是**服从正态分布**的连续随机变量，它的概率密度函数PDF 为fX(x)，经过如下线性变换得到Y”

这段描述的是一般情况

**Comment by Visualize-ML** [comment]
> Ch11 第四节 等式(37) 请问如何理解等式(37)：分子第一项的分子是σ1和σ2相减；分母ρ(1,2)σ1σ2代表的含义

11.36和11.37是用sympy的符号特征值分解算出来的结果，几何上怎么看这两个式子，容我想想

**Comment by Visualize-ML** [comment]
> Ch11 第四节 等式(37) 请问如何理解等式(37)：分子第一项的分子是σ1和σ2相减；分母ρ(1,2)σ1σ2代表的含义

一眼看过去确实感觉11.36和11.37和椭圆有密切关系，感觉把10.26带进去能整理出有意思的式子。

**Comment by Visualize-ML** [comment]
此外，谢谢你读的这么仔细！这些纠错质量都很高，必须要赠书感谢。请把你的邮寄信息发到邮箱，等《编程不难》上架后，我让出版社赠书+签名卡，以表心意。

**Comment by lwy4199** [comment]
> > Ch11 第四节 等式(37) 请问如何理解等式(37)：分子第一项的分子是σ1和σ2相减；分母ρ(1,2)σ1σ2代表的含义
> 
> 一眼看过去确实感觉11.36和11.37和椭圆有密切关系，感觉把10.26带进去能整理出有意思的式子。

感谢您的解答！我尝试一下。

**Comment by lwy4199** [comment]
> 此外，谢谢你读的这么仔细！这些纠错质量都很高，必须要赠书感谢。请把你的邮寄信息发到邮箱，等《编程不难》上架后，我让出版社赠书+签名卡，以表心意。

感谢您的认可，邮寄信息已发送。

**Comment by lwy4199** [comment]
> > Ch9 第八节：从距离到一元高斯分布。“几何变换：平移 + 缩放”小节
> > 描述：“假设 X 是连续随机变量，它的概率密度函数PDF 为fX(x)，经过如下线性变换得到Y”，是否应为“假设 X 是**服从正态分布**的连续随机变量，它的概率密度函数PDF 为fX(x)，经过如下线性变换得到Y”
> 
> 这段描述的是一般情况

这个一般情况的推导过程我查阅资料并手算了一遍，得出了此一般形式，我查阅的推导方式涉及线性映射、反函数性质（单调性）、连续随机变量CDF在约束条件下的变换以及雅可比矩阵这些知识点。这个一般式在本书中是否需要添加额外的推导过程呢，或者推导过程中所涉及的知识点添加到前面的系列丛书和本书相对应的部分中，并在此处位置进行简要推导（可能需要从新设计知识逻辑结构和图例）？

**Comment by Visualize-ML** [comment]
确实，这个推导过程需要其他数学工具，因此免去了。但是，你说得对，有必要提供图解帮助理解。请继续批评指正。

**Comment by lwy4199** [comment]
### Ch14 | Page 17 | 14.5 以椭圆投影为视角看线性变换 | “正”矩形
描述“上一章提到过，图 12 中这个大矩形的面积为4σ1σ2，其对角线长度为矩形对角线长度为”中，大矩形存在歧义，是否改为“马氏距离为1的矩形”？

**Comment by Visualize-ML** [comment]
平面上来看，马氏距离为1描述的是椭圆。但是，你的批评是对的，可以写成“和马氏距离为1椭圆相切的矩形”。
