### ISSUE TITLE
Book5 关于第十八章讲证据因子

### ISSUE THREAD

**Issue by seraphium** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#46]
有个疑问你书里没有提到，最好解释一下，为啥计算贝叶斯分类时候的分母的证据因子需要用全概率定理，引入先验概率。
我的理解要计算fx(x), 跟C无关，那我直接用全部的数据样本用KDE得到fx(x)的边缘概率分布不就得了，为什么还需要分成三个C单独算完了再加起来，引申到后面贝叶斯推断为啥分母要积分，直接算一个fx(x)不行吗？本来也跟theta无关

**Comment by Visualize-ML** [comment]
谢谢你建议。请继续批评指正

**Comment by seraphium** [comment]
所以到底为啥不能直接通过样本算出证据因子，而要引入先验概率来求和/积分？发自我的 iPhone在 2024年1月4日，19:59，Iris Series: Visualize Math -- From Arithmetic Basics to Machine Learning ***@***.***> 写道：﻿
谢谢你建议。请继续批评指正



On Thu, Jan 4, 2024 at 3:10 AM Jackie Zhang ***@***.***>

wrote:

**Comment by Visualize-ML** [comment]
当然，证据因子可以直接算。但是，既然已经前面已经把要算的全部都算了，为啥不用全概率直接求证据因子。
