### ISSUE TITLE
Bk5_Ch23_01.py 执行报错

### ISSUE THREAD

**Issue by yzxzero** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#47]
执行下面2行代码时报错。。
SIGMA = iris_sns.cov()
CORR = iris_sns.corr()

ValueError: could not convert string to float: 'setosa'

**Comment by yzxzero** [comment]
已解决，加了个参数 iris_sns.cov(numeric_only=True)

**Comment by Visualize-ML** [comment]
谢谢你，是的，只有量化数据才能算cov。
