### ISSUE TITLE
Book_Ch8 p4,p5图片和文字不匹配的问题

### ISSUE THREAD

**Issue by jouhpf** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#50]

**Comment by jouhpf** [comment]
作者您好，非常感谢您撰写的这一系列书，让我重新捡起了很多数学知识，本书第八章中第四页上写着下图绿色高亮，但是下方的高亮却是黄色的，请问这里是不是出现了小失误，（也可能是我有黄绿色盲的症状）
![Snipaste_2024-02-05_10-07-17](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/58061729/de2bbd79-cd43-4a90-b7c8-584304c05a2c)
![Snipaste_2024-02-05_10-07-53](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/58061729/1b70f3af-437a-4f47-b81d-560054e52f9a)

**Comment by Visualize-ML** [comment]
谢谢你的肯定！你是对的，确实写错了！也请你继续批评指正，让鸢尾花书越来越好。

拜个早年！Cheers
James
