### ISSUE TITLE
Book5 Ch25 主成分分析 图17的描述

### ISSUE THREAD

**Issue by TruthS1109** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#51]
作者您好！ 

非常感谢分享这么好的书，受益良多！ 

在25.5关于图17的描述中说EF为椭圆长轴，但图中显示为EG，这儿是不是笔误？ 

![image](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/38018322/1b3f6995-3725-4a2d-a71b-a96f49dc347c)

谢谢

**Comment by Visualize-ML** [comment]
谢谢你！

确实写错了，纸质书已经修改了。
