### ISSUE TITLE
ch6图26 图27描述存在疑惑

### ISSUE THREAD

**Issue by dungeon1094** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#52]
![YH1GRY)NQFBD0$41% %{2M](https://github.com/Visualize-ML/Book5_Essentials-of-Probability-and-Statistics/assets/49507327/887d46a4-947d-4926-b105-d333a12462f3)
想请教一下，这里面不是一系列曲线吗，为啥说是直线与水平轴所围成面积是边缘概率呢，我的理解这里的fx1(x1=c)应该等于对联合概率密度函数fx1x2(x1=c)进行x2全区间的积分得到啊，下面的那段话里头的fx2(x2=c)同理，没能理解的了这两句话想表达的意思

**Comment by dungeon1094** [comment]
我理解的是图26的这些曲线与水平轴围成的面积如果沿着x1全部偏积分积起来能得到x2的边缘概率密度函数

**Comment by dungeon1094** [comment]
我好想明白啥意思了，fx1x2(x1=c)这个曲线与水平轴围城面积就是fx1x2(x1=c)进行x2的偏积分，也就是边缘概率fx1(x1=c)

**Comment by Visualize-ML** [comment]
真好！搞清楚就好！你是对的！
