### ISSUE TITLE
姜老师，第五册第四页这里公式有错

### ISSUE THREAD

**Issue by geer1895** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#56]
十一章第4页的第四个公式，最后x₂x₃的系数应该是(p₂,₃-p₁,₃p₁,₂)，书上出现了两个p₂,₃，所以我想应该是公式有点问题。我直接推导的是(p₂,₃-p₁,₃p₁,₂)，不知道对不对。
此外，"统计至简"纸质书(23年10月第一版)第11章"多元高斯分布"这章应该也是没有改，错误的公式是 第289页公式11.4

**Comment by geer1895** [comment]
以及第23章“马氏距离”第10页这里，图七上方的话“马氏距离为正圆”，有些表述不当，应该写成“马氏距离等距线为正圆”更恰当一点。同样，在纸质书的这里（P551)这里也没有改

**Comment by Visualize-ML** [comment]
谢谢你，两处确实有问题。你是对的。请继续批评指正。

Cheers,
