### ISSUE TITLE
第十章P12和P13图中的错误

### ISSUE THREAD

**Issue by tyxbarry** [Visualize-ML/Book5_Essentials-of-Probability-and-Statistics#57]
![image](https://github.com/user-attachments/assets/9efc318f-4adb-4b98-a175-2cb1c3a1026c)
![image](https://github.com/user-attachments/assets/cdacccb9-588e-4fb2-bdd4-32d91bf40438)
这两个图片右侧剖面线的纵坐标最上面应该是1，此处写成了0.1

**Comment by Visualize-ML** [comment]
谢谢你，纸质书已经修改，请继续批评指正

**Comment by tyxbarry** [comment]
邮件已收到，谢谢您的邮件，我会尽快查收回复。

**Comment by tyxbarry** [comment]
邮件已收到，谢谢您的邮件，我会尽快查收回复。
